/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.forum.struts.action;

import java.util.Date;
import java.util.List;

import com.helloweenvsfei.forum.bean.BaseBean;
import com.helloweenvsfei.forum.bean.Board;
import com.helloweenvsfei.forum.bean.Person;
import com.helloweenvsfei.forum.bean.Reply;
import com.helloweenvsfei.forum.bean.Thread;
import com.helloweenvsfei.forum.pagination.Pagination;
import com.helloweenvsfei.forum.service.IBoardService;
import com.helloweenvsfei.forum.service.IPersonService;
import com.helloweenvsfei.forum.service.IReplyService;
import com.helloweenvsfei.forum.service.IThreadService;
import com.helloweenvsfei.forum.struts.util.PersonInfo;
import com.helloweenvsfei.forum.struts.util.PersonUtil;

/**
 * MyEclipse Struts Creation date: 07-04-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/thread" name="threadForm"
 *                input="/form/thread/listThread.jsp" parameter="action"
 *                scope="request" validate="true"
 */
public class ThreadAction extends ForumAction {

	private IThreadService<Thread> threadService;

	private IPersonService<Person> personService;

	private IBoardService<Board> boardService;

	private IReplyService<Reply> replyService;

	

	public IBoardService<Board> getBoardService() {
		return boardService;
	}

	public void setBoardService(IBoardService<Board> boardService) {
		this.boardService = boardService;
	}

	public IPersonService<Person> getPersonService() {
		return personService;
	}

	public void setPersonService(IPersonService<Person> personService) {
		this.personService = personService;
	}

	public IReplyService<Reply> getReplyService() {
		return replyService;
	}

	public void setReplyService(IReplyService<Reply> replyService) {
		this.replyService = replyService;
	}

	public IThreadService<Thread> getThreadService() {
		return threadService;
	}

	public void setThreadService(IThreadService<Thread> threadService) {
		this.threadService = threadService;
	}

	public String list() {
		// TODO Auto-generated method stub
		return null;
	}

}